title: cryptoanarchy.wiki
description: Arise, you have nothing to lose but your barbed wire fences!
author: cryptoanarchy.wiki
github: https://github.com/cryptoanarchywiki/cryptoanarchywiki.github.io
about: Arise, you have nothing to lose but your barbed wire fences!
disqus_shortname: 
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/_cryptoanarchy"
    - icon: fa-facebook
      link: "https://www.facebook.com/cryptoanarchy.wiki"
    - icon: fa-github
      link: "https://github.com/cryptoanarchywiki"

share:
  twitter_username: _cryptoanarchy
  fb_appid: 

urls:
    - text: About Us
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://cryptoanarchywiki.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
