title: cryptoanarchy.wiki
description: Arise, you have nothing to lose but your barbed wire fences!
author: cryptoanarchy.wiki
github: https://github.com/cryptoanarchywiki/cryptoanarchywiki.github.io
about: Arise, you have nothing to lose but your barbed wire fences!
disqus_shortname: 
google_analytics: UA-77476019-2
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

social:
    - icon: fa-twitter
      link: "https://twitter.com/_cryptoanarchy"
    - icon: fa-facebook
      link: "https://www.facebook.com/cryptoanarchy.wiki"
    - icon: fa-github
      link: "https://github.com/cryptoanarchywiki"

share:
  twitter_username: _cryptoanarchy
  fb_appid: 

urls:
    - text: XML Feed
      url: /feed.xml

similar_resources:
    - text: Lopp's Bitcoin Resources
      url: "https://lopp.net/bitcoin.html"
    - text: Satoshi Nakamoto Institute
      url: "https://nakamotoinstitute.org/"
    - text: "Activism.net: Cypherpunks"
      url: "https://www.activism.net/cypherpunk/"

url: "https://cryptoanarchywiki.github.io"
baseurl: ""
per_page: 20
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
